
mykit:
  delay:
    logpath: ../logs
    registry:
      enable: false
      namespace: io-mykit-delay
      serverList: 10.2.2.231:2181
    rocketmq:
      namesrvAddr: 127.0.0.1:9876
      filterSourceRoot: /home/
    rqueue:
      #是否已集群模式运行 会涉及到分布式锁竞争的情况 默认为false
      cluster: false
      name: mykit-delay
      bucketSize: 4

spring:
  jmx:
    enabled: true
  application:
    name: 'mykit'
    version: '1.0.0'
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mykit_delay?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 30
    initialSize: 3
    maxWait: 60000
    maxIdle: 30
    minIdle: 3
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    #        host: localhost
    #        password: aJjbuDRYw4
    #        port: 6380
    timeout: 60000
    database: 22
    cluster:
      nodes:
        - 10.2.2.231:7001
        - 10.2.2.231:7002
        - 10.2.2.231:7003
        - 10.2.2.231:7004
        - 10.2.2.231:7005
        - 10.2.2.231:7006
    pool:
      max-idle: 300
      min-idle: 10
      max-active: 200
      max-wait: 10000

server:
  port: 6357

logging:
  config: classpath:config/logback.xml
